{
    "load": {
        "insertComplete": true,
        "Exceptions": {
            "total": 0
        },
        "insertRetryError": 0
    },
    "run": {
        "executionTimeReached": false,
        "Exceptions": {
            "total": 3486,
            "\tat com.datastax.driver.core.Responses$Error.asException": 498,
            "com.datastax.driver.core.exceptions.WriteTimeoutException": 498,
            "Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException": 996,
            "\tat com.datastax.driver.core.exceptions.WriteTimeoutException": 1494
        },
        "insertRetryError": 0,
        "INSERT-FAILED": 498,
        "READ-FAILED": 763267
    }
}